IF (HIREIDS_INCLUDE_DIR)
    # Already in cache, be silent
    SET(HIREDIS_FIND_QUIETLY TRUE)
ENDIF (HIREIDS_INCLUDE_DIR)

FIND_PATH(HIREIDS_INCLUDE_DIR hiredis.h
        /usr/local/include
        /usr/include
        )
SET(HIREDIS_NAME hiredis)

FIND_LIBRARY(HIREDIS_LIBRARY
        NAMES ${HIREDIS_NAME}
        PATHS /usr/lib /usr/local/lib
        )

IF (HIREIDS_INCLUDE_DIR AND HIREDIS_LIBRARY)
    SET(HIREDIS_FOUND TRUE)
    SET( HIREDIS_LIBRARIES ${HIREDIS_LIBRARY} )
ELSE (HIREIDS_INCLUDE_DIR AND HIREDIS_LIBRARY)
    SET(HIREDIS_FOUND FALSE)
    SET( HIREDIS_LIBRARIES )
ENDIF (HIREIDS_INCLUDE_DIR AND HIREDIS_LIBRARY)

#如果找到并且没有设置QUIET，则输出搜到动态库路径
#如果找不到就输出错误信息
IF (HIREDIS_FOUND)
    IF (NOT HIREDIS_FIND_QUIETLY)
        MESSAGE(STATUS "Found Hiredis: ${HIREDIS_LIBRARY}")
    ENDIF (NOT HIREDIS_FIND_QUIETLY)
ELSE (HIREDIS_FOUND)
    IF (HIREDIS_FIND_REQUIRED)
        MESSAGE(STATUS "Looked for hirdis libraries named ${HIREDIS_NAME}.")
        MESSAGE(FATAL_ERROR "Could NOT find hiredis library")
    ENDIF (HIREDIS_FIND_REQUIRED)
ENDIF (HIREDIS_FOUND)
